version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
